In [54]:
import numpy as np 
np.set_printoptions(linewidth=150,precision=4)

# Simple 10 State example 

In [82]:
initial_state = np.array([0,0,1,0,0,0,0,0,0,0]).T

probability_matrix = np.ones(shape=(10,10))

for i in range(10):
    probability_matrix[i,:] /= (10*(i+1))

for i in range(10):
    probability_matrix[:,i] *= i+1

upper_triangle = np.triu_indices(10)
probability_matrix[upper_triangle] = 1/10.

# normalize
for i in range(10):
    probability_matrix[i] /= np.sum(probability_matrix[i])

probability_matrix = probability_matrix

print(probability_matrix)


[[0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1    0.1   ]
 [0.0526 0.1053 0.1053 0.1053 0.1053 0.1053 0.1053 0.1053 0.1053 0.1053]
 [0.037  0.0741 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111]
 [0.0294 0.0588 0.0882 0.1176 0.1176 0.1176 0.1176 0.1176 0.1176 0.1176]
 [0.025  0.05   0.075  0.1    0.125  0.125  0.125  0.125  0.125  0.125 ]
 [0.0222 0.0444 0.0667 0.0889 0.1111 0.1333 0.1333 0.1333 0.1333 0.1333]
 [0.0204 0.0408 0.0612 0.0816 0.102  0.1224 0.1429 0.1429 0.1429 0.1429]
 [0.0192 0.0385 0.0577 0.0769 0.0962 0.1154 0.1346 0.1538 0.1538 0.1538]
 [0.0185 0.037  0.0556 0.0741 0.0926 0.1111 0.1296 0.1481 0.1667 0.1667]
 [0.0182 0.0364 0.0545 0.0727 0.0909 0.1091 0.1273 0.1455 0.1636 0.1818]]


In [89]:
trial = 5
current_state = initial_state 
print(current_state)
for t in range(trial):
    current_state = np.dot(probability_matrix.T, current_state)
    print(current_state)

[0 0 1 0 0 0 0 0 0 0]
[0.037  0.0741 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111 0.1111]
[0.0287 0.0537 0.0748 0.0918 0.1056 0.1165 0.125  0.1312 0.1353 0.1373]
[0.0265 0.0501 0.0709 0.0889 0.1042 0.1168 0.1269 0.1344 0.1394 0.1419]
[0.0261 0.0495 0.0702 0.0884 0.1039 0.1169 0.1272 0.135  0.1401 0.1427]
[0.026  0.0494 0.0701 0.0883 0.1039 0.1169 0.1273 0.135  0.1402 0.1428]
